programs:
  web-server:
    cmd: "node server.js"
    workingdir: "./services/web"
    autostart: true
    numprocs: 2
    autorestart: unexpected
    exitcodes: [0]
    startretries: 3
    starttime: 5
    stopsignal: SIGTERM
    stoptime: 5
    stdout: "./logs/web/web.stdout.log"
    stderr: "./logs/web/web.stderr.log"
    env:
      PORT: "5000"
    umask: "026"
    tags: [web, frontend]

  job-worker:
    cmd: "python3 worker.py"
    numprocs: 3
    workingdir: "./services/worker"
    autostart: true
    autorestart: never
    exitcodes: [0]
    startretries: 3
    starttime: 4
    stopsignal: SIGINT
    stoptime: 7
    stdout: "./logs/worker/worker.stdout.log"
    stderr: "./logs/worker/worker.stderr.log"
    env:
      WORKER_MODE: "parallel"
    umask: "027"
    tags: [worker, backend]

  mailer:
    cmd: "bash run_mailer.sh"
    numprocs: 1
    workingdir: "./scripts"
    autostart: false
    autorestart: never
    exitcodes: [0]
    startretries: 2
    starttime: 2
    stopsignal: SIGTERM
    stoptime: 3
    stdout: "./logs/mailer/mailer.stdout.log"
    stderr: "./logs/mailer/mailer.stderr.log"
    env:
      MAIL_ENV: "production"
    umask: "077"
    tags: [mail, backend]

  debug-task:
    cmd: "node debug.js"
    numprocs: 1
    workingdir: "./services/debug"
    autostart: true
    autorestart: always
    exitcodes: [0]
    startretries: 1
    starttime: 1
    stopsignal: SIGKILL
    stoptime: 1
    stdout: "./logs/debug/debug.stdout.log"
    stderr: "./logs/debug/debug.stderr.log"
    env:
      DEBUG: "true"
    umask: "000"
    tags: [debug, test]
